pipeline {
    agent any
    stages {
        stage('Docker Push'){
            steps{
                withCredentials([
                    usernamePassword(
                        credentialsId: 'dockerhub-creds',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS'
                    )
                ]) {
                    sh '''
                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                        
                        docker tag myapp:latest $DOCKER_USER/myapp:latest
                        
                        docker push $DOCKER_USER/myapp:latest
                    '''
                }
                
            }
        }
    }
}