pipeline{
    agent any
    stages {
        stage('Build') {
            steps { 

                dir('sample-apps/java-app') {
                    sh 'mvn clean package -DskipTests'
                    }
                }       
            }
        stage('Test in Parallel') {
            parallel {
                stage('Unit Tests') {
                    steps { 
                        dir('sample-apps/java-app') {
                            sh 'mvn test '
                        }
                    }
                }
                stage('Security Scan') {
                    steps {
                        dir('sample-apps/java-app') {
                            sh 'mvn dependency-check:check' 
                        }
                    }
                 }
            }
        }
    }
}